"use strict";
const SECONDINMILLISECONDS = 1e3;
const MINUTEINMILLISECONDS = 60 * SECONDINMILLISECONDS;

module.exports = {
  SECONDINMILLISECONDS,
  MINUTEINMILLISECONDS,
  GIGABYTEINBYTES: 1073741824,
  GATEWAYURLPARAMS: "?v=6&encoding=json",
  DISCORDURI: "https://discordapp.com/api/v6/",
  WEBSOCKETURIFAILRETRY: 10 * SECONDINMILLISECONDS,
  REQUESTTIMEOUTDEFAULT: 5 * MINUTEINMILLISECONDS,
  MINIMUMIDENTIFYWAIT: 6 * SECONDINMILLISECONDS,
  OPCODES: {
    DISPATCH: 0,
    HEARTBEAT: 1,
    IDENTIFY: 2,
    RESUME: 6,
    INVALID_SESSION: 9,
    HELLO: 10,
    HEARTBEAT_ACK: 11
  },
  // Discord epoch (2015-01-01T00:00:00.000Z)
  EPOCH: 1420070400000,
  PERMISSIONS: {
    ADMINISTRATOR: 0x8
  },
  DISCORDIMAGEBASEURL: "https://cdn.discordapp.com/"
};
